services:
  server:
    build:
      context: .
      args:
        USER_NAME: docker
        GROUP_NAME: docker
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    # hostname: server
    ports:
      - 8080:8080
    volumes:
      - .:/home/docker/app
    user: ${UID}:${GID}
