services:
  server:
    build:
      context: .
      args:
        USER_NAME: docker
        GROUP_NAME: docker
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    # hostname: server
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - SUPABASE_API_URL=${SUPABASE_API_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
    ports:
      - 8080:8080
    volumes:
      - .:/home/docker/app
    user: ${UID}:${GID}
