services:
  scala:
    build:
      context: .
      args:
        USER_NAME: docker
        GROUP_NAME: docker
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    hostname: scala
    environment:
      - JDBC_URL=${JDBC_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/home/docker/app
    user: ${UID}:${GID}
